README.md
=> Updated Readme UI

src/app/dto/referenceDataResponseDto.ts, src/app/reference-data/reference-data.component.html, src/app/reference-data/reference-data.component.ts, src/app/services/realestate-api.service.ts
Added a filter to Reference Data list
=> UI - Filter Reference Data List

src/app/modals/property-management-modal/property-management-modal.component.html, src/app/modals/property-management-modal/property-management-modal.component.ts
Get the reference data, to populate the dropdowns of the Property Management modal.
=> UI - Add Property Modal to load dropdowns with ref data

src/app/modals/property-management-modal/property-management-modal.component.html, src/form/form.service.ts
Make amenities optional in Property Management page Modal.
=> UI - Add Property Modal | Make amenities optional

src/app/app.module.ts, src/app/customer-management/customer-management.component.html, src/app/customer-management/customer-management.component.ts, src/app/modals/customer-management-modal/customer-management-modal.component.html, src/app/modals/customer-management-modal/customer-management-modal.component.spec.ts, src/app/modals/customer-management-modal/customer-management-modal.component.ts, src/form/form.service.ts
Added files:
- customer-management-modal.component.css
- customer-management-modal.component.html
- customer-management-modal.component.specs.ts
- customer-management-modal.component.ts
=> Added Modal components for the customers page

src/app/modals/customer-management-modal/customer-management-modal.component.html, src/app/modals/customer-management-modal/customer-management-modal.component.ts, src/app/services/customer-api.service.ts
Added function to post customers data
=> Added post method in the customers modal

src/app/reference-data/reference-data.component.css, src/app/reference-data/reference-data.component.html, src/app/reference-data/reference-data.component.ts, src/app/services/reference-data-api.service.ts
Added DELETE method to Reference Data page and a toast when we delete a reference data.
=> UI - Delete Reference Data

src/app/property-management/property-management.component.html
Updated "Contruction Year" to "Construction Year" in Property Management Page.
=>  UI - BUG Property Management

src/app/property-management/property-management.component.css, src/app/property-management/property-management.component.html
Reverted delete property button change.
=> BUG - UI -> Revert delete property button change

src/app/customer-management/customer-management.component.ts, src/app/modals/customer-management-modal/customer-management-modal.component.html, src/app/modals/customer-management-modal/customer-management-modal.component.ts, src/app/modals/reference-data-modal/reference-data-modal.component.html, src/app/modals/reference-data-modal/reference-data-modal.component.ts, src/app/property-management/property-management.component.ts, src/app/reference-data/reference-data.component.ts
- Reference Data;
- Customer Management.
-Code Cleaning
=> Fixed list refresh after post on management components.

src/app/models/property-management-model.ts, src/app/property-management/property-management.component.html, src/app/property-management/property-management.component.ts, src/app/services/property-management-api.service.spec.ts, src/app/services/property-management-api.service.ts
Fetch all property management data to accordion header.
=> UI - Get All Properties 

src/app/property-management/property-management.component.html, src/app/property-management/property-management.component.ts, src/app/services/property-management-api.service.ts
Added method get to property data by id and show them when the accordian button was clicked.
=>  UI - Get Property By Id

src/form/form.service.ts
Added customer email address validation improvement.
=> UI - Add Customer Email Address Field Improvement

src/app/customer-management/customer-management.component.ts
Fixed the name of the function loadCUstomerData > loadCustomerData
=> UI/FIX Customer component function name

src/app/agent-management/agent-management.component.html, src/app/app.routes.ts, src/app/models/agent-model.ts, src/app/services/agent.service.ts, src/app/views/agent-view/agent-view.component.html, src/app/views/agent-view/agent-view.component.spec.ts, src/app/views/agent-view/agent-view.component.ts
Added a view page for agents:
- new view component
- routed from click on view button
- HTTP GET and new GetAgentById() method
=> Created view page for agent in the UI

src/app/modals/real-estate-management-modal/real-estate-management-modal.component.html, src/app/modals/real-estate-management-modal/real-estate-management-modal.component.ts, src/app/models/real-estate-management-model.ts
Removed agent id from real estate components and models.
=> Removed agent Id from realestate components

src/app/app.module.ts, src/app/app.routes.ts, src/app/home/home.component.ts, src/app/models/visit-request-model.ts, src/app/services/visit-request.service.spec.ts, src/app/services/visit-request.service.ts, src/app/visit-request-management/visit-request-management.component.html, src/app/visit-request-management/visit-request-management.component.spec.ts, src/app/visit-request-management/visit-request-management.component.ts
=> UI - Visit Request Component

src/app/customer/components/customer-details/customer-details.component.html, src/app/customer/components/customer-details/customer-details.component.ts, src/app/customer/modals/customer-management-modal/customer-management-modal.component.html, src/app/customer/modals/customer-management-modal/customer-management-modal.component.ts
Added visibilty toggle for the password field in the customer modal
=> UI - Customer Details Improvement

src/app/common/services/form/form.service.ts, src/app/customer/modals/customer-management-modal/customer-management-modal.component.html
Added Customer Validators in the customer form
=> UI - Customer Validators

src/app/common/services/form/form.service.ts
Added validator for description length in Reference Data Modal:
- Min Length: 2 characters
- Max Length: 50 characters
Displays error message in the modal if it doesn't apply the giving rules
=> UI - description length validator in Reference Data Modal

src/app/agent/modals/agent-modal/agent-modal.component.html, src/app/common/services/form/form.service.ts, src/app/customer/components/customer-details/customer-details.component.html, src/app/customer/components/customer-details/customer-details.component.ts, src/app/customer/modals/customer-management-modal/customer-management-modal.component.html, src/app/customer/modals/customer-management-modal/customer-management-modal.component.ts
Fixed validators forms for customer, agent and real estate and fixed added toggle visability for password field in the details customer page and modal
=> UI - Real Estate Validators Form

src/app/visit-request/components/visit-request-details/visit-request-details.component.html
Added a button to return to "/visit-request" page in the visit request details page
=> UI - Back Button Visit Requests Details Page

src/app/visit-request/components/visit-request-details/visit-request-details.component.html, src/app/visit-request/components/visit-request-details/visit-request-details.component.ts, src/app/visit-request/services/visit-request.service.ts
Added funcionality for the confirmation button in the visit requests
=> UI - Confirmation Button Visit Requests

src/app/visit-request/components/visit-request-details/visit-request-details.component.html, src/app/visit-request/components/visit-request-details/visit-request-details.component.ts
Reverts estagio-2023/realestate-ui#127
=> Revert "UI/visit-request time format"

src/app/visit-request/components/modals/visit-request-management-modal/visit-request-management-modal.component.ts
Fixed from realestate to realEstate
=> Ui - Bug Visit Request Modal Component

src/app/visit-request/components/visit-request-details/visit-request-details.component.ts
Removed unecesary form.reset()
=> UI - Bug Form Reset Visit Request

src/app/agent/modals/agent-modal/agent-modal.component.html, src/app/customer/modals/customer-management-modal/customer-management-modal.component.html, src/app/realestate/modals/real-estate-management-modal/real-estate-management-modal.component.html, src/app/visit-request/components/modals/visit-request-management-modal/visit-request-management-modal.component.html
Fixed agent, customer, real estate and visit request modal from col-md-4 w-100 to col-md-12.
=> UI - Bug Fixed Modals
